export const wordBank: Record<string, string[]> = {
  Películas: [
    "El Padrino",
    "Titanic",
    "Avatar: Fire and Ash",
    "Avengers: Endgame",
    "Jurassic Park",
    "Star Wars",
    "Batman: El Caballero de la noche",
    "Forrest Gump",
    "Gladiador",
    "El Señor de los Anillos",
    "Harry Potter y la piedra filosofal",
    "Matrix",
    "El Rey León",
    "Toy Story",
    "Buscando a Nemo",
    "Frozen",
    "Shrek",
    "Los Increíbles",
    "Up",
    "Coco",
    "Interestelar",
    "Origen",
    "Parásitos",
    "Joker",
    "Spider-Man: No Way Home",
    "Iron Man",
    "Black Panther",
    "Doctor Strange",
    "Deadpool",
    "Rápidos y Furiosos",
    "Misión Imposible",
    "Piratas del Caribe: La maldición del Perla Negra",
    "Rocky",
    "Rambo",
    "Terminator",
    "Volver al Futuro",
    "Indiana Jones y los cazadores del arca perdida",
    "E.T., el extraterrestre",
    "Tiburón",
    "Efecto mariposa",
    "El sexto sentido",
    "007: Skyfall",
    "El club de la pelea",
    "El lobo de Wall Street",
    "El Gran Gatsby",
    "El Perfume: Historia de un asesino",
    "Psicosis",
    "El resplandor",
    "Django sin cadenas",
    "Bastardos sin gloria",
    "Los 3 chiflados",
    "Braveheart",
    "300",
    "La La Land",
    "Whiplash",
    "El pianista",
    "Matilda",
    "Búsqueda implacable",
    "The life of Pi",
    "Mad Max: Furia en el camino",
    "John Wick",
    "El Conjuro",
    "It",
    "Scream",
    "El Exorcista",
    "Blade Runner",
    "Alien: El octavo pasajero",
    "Depredador",
    "El Código Da Vinci",
    "Los Juegos del Hambre",
    "Logan",
    "Wonder Woman",
    "Aquaman",
    "Thor",
    "Guardianes de la Galaxia",
    "Transformers",
    "Avatar: La forma del agua",
    "Bohemian Rhapsody",
    "Narnia: El león, la bruja y el ropero",
    "El Laberinto del Fauno",
    "Roma",
    "Her",
    "The Truman Show",
    "Hidden Figures",
    "La Vida es Bella",
    "Noé",
    "Una niñera a prueba de balas",
    "Resident Evil",
    "El marciano",
    "Top Gun",
    "Parasitos",
    "El Origen de los Guardianes",
    "La Teoría del Todo",
    "Scott Pilgrim vs. the World",
    "El Quinto Elemento",
    "Suicide Squad",
    "Black Swan"
  ],
  Series: [
    "Stranger Things",
    "Breaking Bad",
    "The Crown",
    "La Casa de Papel",
    "Narcos",
    "Chernobyl",
    "Game of Thrones",
    "The Sopranos",
    "Friends",
    "The Office",
    "Westworld",
    "Black Mirror",
    "Dark",
    "Peaky Blinders",
    "Mindhunter",
    "Ozark",
    "Élite",
    "The Mandalorian",
    "Vikings",
    "The Witcher",
    "Better Call Saul",
    "Una serie de eventos desafortunados",
    "House of Cards",
    "Downton Abbey",
    "Sherlock",
    "Si la vida te da mandarinas",
    "The Boys",
    "Agente nocturno",
    "Lucifer",
    "Dragon Ball Z",
    "Dexter",
    "The Walking Dead",
    "This Is Us",
    "The Umbrella Academy",
    "Succession",
    "Mr. Robot",
    "The Haunting of Hill House",
    "Los Simuladores",
    "13 Reasons Why",
    "House",
    "X-men 97",
    "The Flash",
    "Prison Break",
    "How I Met Your Mother",
    "Modern Family",
    "The Simpsons",
    "Rick y Morty",
    "BoJack Horseman",
    "Twin Peaks",
    "Mad Men",
    "The West Wing",
    "Homeland",
    "Borgen",
    "The Good Place",
    "Naruto Shippuden",
    "Lost",
    "Fringe",
    "The X-Files",
    "Avatar: La leyenda de Aang",
    "One Piece",
    "Attack on Titan",
    "My Hero Academia",
    "Death Note",
    "Cobra Kai",
    "The Shield",
    "Luther",
    "True Blood",
    "The Leftovers",
    "The Vampire Diaries",
    "Jessica Jones",
    "Hannibal",
    "Grey's Anatomy",
    "Shameless",
    "Silicon Valley",
    "Parks and Recreation",
    "The Big Bang Theory",
    "The Wire",
    "Seinfeld",
    "Brooklyn Nine-Nine",
    "The Last of Us",
    "Euphoria",
    "The Bear",
    "House of the Dragon",
    "Wednesday",
    "Bridgerton",
    "The Sandman",
    "Arcane",
    "Invincible",
    "The Queen's Gambit",
    "Money Heist: Korea",
    "Sense8",
    "Rome",
    "Spartacus",
    "Supernatural",
    "The OA",
    "Ted Lasso",
    "Yellowstone"
  ],
  Personajes: [
    "Vito Corleone",
    "Michael Corleone",
    "Tony Montana",
    "Rocky Balboa",
    "Rambo",
    "Darth Vader",
    "Luke Skywalker",
    "Princesa Leia",
    "Han Solo",
    "Indiana Jones",
    "Forrest Gump",
    "Neo",
    "Terminator",
    "Ellen Ripley",
    "Jack Dawson",
    "Joker",
    "Batman",
    "Spider-Man",
    "Iron Man",
    "Capitán América",
    "Thor",
    "Black Panther",
    "Doctor Strange",
    "Deadpool",
    "Wolverine",
    "Harry Potter",
    "Hermione Granger",
    "Ron Weasley",
    "Gandalf",
    "Frodo Bolsón",
    "Aragorn",
    "Legolas",
    "Capitán Jack Sparrow",
    "Elsa",
    "Mystique",
    "Simba",
    "Woody",
    "Buzz Lightyear",
    "Shrek",
    "Fiona",
    "Optimus Prime",
    "John Wick",
    "Maximus",
    "William Wallace",
    "Gladiador Máximo",
    "Travis Bickle",
    "El Padrino",
    "Hannibal Lecter",
    "Clarice Starling",
    "Freddy Krueger",
    "Michael Myers",
    "Jason Voorhees",
    "El Exorcista (Regan)",
    "Pennywise",
    "James Bond",
    "Rocky Dennis",
    "Marty McFly",
    "Doc Brown",
    "E.T.",
    "King Kong",
    "Godzilla",
    "Sherlock Holmes",
    "Drácula",
    "Frankenstein",
    "Tarzán",
    "Aladdin",
    "Genio",
    "Mufasa",
    "Scar",
    "Maléfica",
    "Cruella de Vil",
    "Cenicienta",
    "Blancanieves",
    "La Mujer Maravilla",
    "Aquaman",
    "Lara Croft",
    "Katniss Everdeen",
    "Jack Sparrow",
    "Edward Scissorhands",
    "El Lobo de Wall Street (Jordan Belfort)",
    "Tyler Durden",
    "Patrick Bateman",
    "El Hombre Araña",
    "Black Widow",
    "Thanos",
    "Hulk",
    "Dr. Emmett Brown",
    "Norman Bates",
    "El T-1000",
    "Robocop",
    "El Zorro",
    "Beetlejuice",
    "Rocky Balboa Jr.",
    "Anakin Skywalker",
    "Obi-Wan Kenobi",
    "Capitana Marvel"
  ],
  Celebridades: [
    "Michael Jackson",
    "Elvis Presley",
    "Madonna",
    "Beyoncé",
    "Taylor Swift",
    "Rihanna",
    "Ariana Grande",
    "Lady Gaga",
    "Shakira",
    "Jennifer Lopez",
    "Justin Bieber",
    "Bruno Mars",
    "Drake",
    "The Weeknd",
    "Eminem",
    "Ed Sheeran",
    "Adele",
    "Kanye West",
    "Bad Bunny",
    "Karol G",
    "Leonardo DiCaprio",
    "Brad Pitt",
    "Angelina Jolie",
    "Tom Cruise",
    "Johnny Depp",
    "Will Smith",
    "Dwayne Johnson",
    "Robert Downey Jr.",
    "Scarlett Johansson",
    "Jennifer Lawrence",
    "Emma Watson",
    "Keanu Reeves",
    "Morgan Freeman",
    "Tom Hanks",
    "Meryl Streep",
    "Natalie Portman",
    "Chris Hemsworth",
    "Zendaya",
    "Margot Robbie",
    "Ryan Reynolds",
    "Lionel Messi",
    "Cristiano Ronaldo",
    "Neymar",
    "Kylian Mbappé",
    "LeBron James",
    "Michael Jordan",
    "Serena Williams",
    "Roger Federer",
    "Rafael Nadal",
    "Tiger Woods",
    "Muhammad Ali",
    "Usain Bolt",
    "Simone Biles",
    "Stephen Curry",
    "Lewis Hamilton",
    "David Beckham",
    "Pelé",
    "Diego Maradona",
    "Freddie Mercury",
    "Bob Marley",
    "Whitney Houston",
    "Prince",
    "David Bowie",
    "Kurt Cobain",
    "Mick Jagger",
    "Paul McCartney",
    "John Lennon",
    "Britney Spears",
    "Christina Aguilera",
    "Billie Eilish",
    "Selena Gomez",
    "Kim Kardashian",
    "Kylie Jenner",
    "Oprah Winfrey",
    "Ellen DeGeneres",
    "Jimmy Fallon",
    "MrBeast",
    "PewDiePie",
    "Mark Zuckerberg",
    "Elon Musk",
    "Bill Gates",
    "Steve Jobs",
    "Jeff Bezos",
    "Barack Obama",
    "Donald Trump",
    "Joe Biden",
    "Vladimir Putin",
    "Papa Francisco",
    "Reina Isabel II",
    "Princesa Diana",
    "Jackie Chan",
    "Bruce Lee",
    "Sylvester Stallone",
    "Arnold Schwarzenegger",
    "Jim Carrey",
    "Robert De Niro",
    "Al Pacino",
    "Quentin Tarantino"
  ],
  Animales: [
    "Perro",
    "Gato",
    "León",
    "Tigre",
    "Elefante",
    "Jirafa",
    "Cebra",
    "Caballo",
    "Vaca",
    "Toro",
    "Oveja",
    "Cabra",
    "Cerdo",
    "Conejo",
    "Lobo",
    "Zorro",
    "Oso",
    "Panda",
    "Koala",
    "Canguro",
    "Chimpancé",
    "Gorila",
    "Orangután",
    "Rinoceronte",
    "Hipopótamo",
    "Cocodrilo",
    "Aligátor",
    "Serpiente",
    "Águila",
    "Halcón",
    "Búho",
    "Loro",
    "Pingüino",
    "Avestruz",
    "Pavo real",
    "Gallina",
    "Gallo",
    "Pato",
    "Cisne",
    "Tiburón",
    "Delfín",
    "Ballena",
    "Orca",
    "Pulpo",
    "Calamar",
    "Medusa",
    "Estrella de mar",
    "Caballito de mar",
    "Foca",
    "León marino",
    "Morsa",
    "Camello",
    "Llama",
    "Alpaca",
    "Ardilla",
    "Castor",
    "Mapache",
    "Hurón",
    "Erizo",
    "Hámster",
    "Ratón",
    "Rata",
    "Murciélago",
    "Pantera",
    "Leopardo",
    "Guepardo",
    "Hiena",
    "Bisonte",
    "Ciervo",
    "Venado",
    "Antílope",
    "Búfalo",
    "Carnero",
    "Chivo",
    "Puma",
    "Jaguar",
    "Mono",
    "Perezoso",
    "Tortuga",
    "Iguana",
    "Camaleón",
    "Rana",
    "Sapo",
    "Salamandra",
    "Cangrejo",
    "Langosta",
    "Hormiga",
    "Abeja",
    "Mariposa",
    "Escorpión",
    "Araña",
    "Caracol",
    "Babosa",
    "Gaviota",
    "Colibrí",
    "Cuervo",
    "Paloma"
  ],
  Comida: [
    "Pizza",
    "Hamburguesa",
    "Hot dog",
    "Sushi",
    "Ramen",
    "Tacos",
    "Burrito",
    "Quesadilla",
    "Nachos",
    "Paella",
    "Tortilla española",
    "Gazpacho",
    "Pasta",
    "Lasaña",
    "Espagueti",
    "Risotto",
    "Gnocchi",
    "Ravioli",
    "Pollo frito",
    "Alitas de pollo",
    "Barbacoa",
    "Costillas BBQ",
    "Filete",
    "Ensalada César",
    "Sopa de tomate",
    "Crema de champiñones",
    "Curry",
    "Ají de gallina",
    "Falafel",
    "Hummus",
    "Kebab",
    "Shawarma",
    "Empanadas",
    "Arepas",
    "Ceviche",
    "Tamales",
    "Churros",
    "Croissant",
    "Baguette",
    "Panqueques",
    "Waffles",
    "Donas",
    "Brownies",
    "Cupcakes",
    "Pastel de chocolate",
    "Cheesecake",
    "Tiramisú",
    "Gelato",
    "Helado",
    "Flan",
    "Arroz con leche",
    "Mousse de chocolate",
    "Macarrones",
    "Pudín",
    "Galletas",
    "Sandwich",
    "Club sandwich",
    "Tostadas",
    "Huevos revueltos",
    "Omelette",
    "Bacon",
    "Salchichas",
    "Mariscos",
    "Langosta",
    "Camarones",
    "Pulpo a la gallega",
    "Sashimi",
    "Tempura",
    "Dim sum",
    "Rollitos primavera",
    "Pad Thai",
    "Pho",
    "Bibimbap",
    "Kimchi",
    "Goulash",
    "Fondue",
    "Ratatouille",
    "Pierogi",
    "Feijoada",
    "Asado",
    "Milanesa",
    "Chili con carne",
    "Guacamole",
    "Nachos con queso",
    "Papas fritas",
    "Puré de papa",
    "Arroz frito",
    "Arroz blanco",
    "Lentejas",
    "Sopa miso",
    "Enchiladas",
    "Fajitas",
    "Poke",
    "Tarta de manzana",
    "Crepes",
    "Salmón a la plancha",
    "Pollo asado",
    "Chaufa"
  ],
  Disney: [
    // Personajes Clásicos
    "Mickey Mouse - Mickey Mouse Clubhouse",
    "Minnie Mouse - Mickey Mouse Clubhouse",
    "Donald Duck - Mickey Mouse Clubhouse",
    "Goofy - Mickey Mouse Clubhouse",
    "Pluto - Mickey Mouse Clubhouse",
    "Pinocho - Pinocho",
    "Dumbo - Dumbo",
    "Bambi - Bambi",
    "Peter Pan - Peter Pan",
    "Campanilla - Peter Pan",
    "Alicia - Alicia en el País de las Maravillas",
    "El Sombrerero Loco - Alicia en el País de las Maravillas",

    // Princesas y sus personajes
    "Blancanieves - Blancanieves y los Siete Enanos",
    "El Príncipe - Blancanieves y los Siete Enanos",
    "El Espejo Mágico - Blancanieves y los Siete Enanos",
    "La Reina Malvada - Blancanieves y los Siete Enanos",
    "Cenicienta - Cenicienta",
    "El Príncipe Azul - Cenicienta",
    "El Hada Madrina - Cenicienta",
    "La Zapatilla de Cristal - Cenicienta",
    "Aurora - La Bella Durmiente",
    "Maléfica - La Bella Durmiente",
    "Flora - La Bella Durmiente",
    "Fauna - La Bella Durmiente",
    "Primavera - La Bella Durmiente",
    "Ariel - La Sirenita",
    "Príncipe Eric - La Sirenita",
    "Úrsula - La Sirenita",
    "Sebastián - La Sirenita",
    "Flounder - La Sirenita",
    "Belle - La Bella y la Bestia",
    "La Bestia - La Bella y la Bestia",
    "Gastón - La Bella y la Bestia",
    "Lumière - La Bella y la Bestia",
    "Jasmine - Aladdin",
    "Aladdin - Aladdin",
    "Jafar - Aladdin",
    "Iago - Aladdin",
    "Abu - Aladdin",
    "Rajah - Aladdin",
    "La Lámpara Maravillosa - Aladdin",
    "Genio - Aladdin",
    "Pocahontas - Pocahontas",
    "John Smith - Pocahontas",
    "Meeko - Pocahontas",
    "Mulán - Mulán",
    "Li Shang - Mulán",
    "Mushu - Mulán",
    "Tiana - La Princesa y el Sapo",
    "Príncipe Naveen - La Princesa y el Sapo",
    "Dr. Facilier - La Princesa y el Sapo",
    "Carlota - La Princesa y el Sapo",
    "Louis - La Princesa y el Sapo",
    "Rapunzel - Enredados",
    "Flynn Rider - Enredados",
    "Pascal - Enredados",
    "Gothel - Enredados",
    "Mérida - Valiente",
    "Elsa - Frozen",
    "Anna - Frozen",
    "Kristoff - Frozen",
    "Olaf - Frozen",
    "Sven - Frozen",
    "Hans - Frozen",
    "Moana - Moana",
    "Maui - Moana",
    "Tamatoa - Moana",
    "Te Kā - Moana",
    "Abuela Motunui - Moana",
    "Raya - Raya y el Último Dragón",
    "Sisu - Raya y el Último Dragón",

    // El Rey León
    "Simba - El Rey León",
    "Mufasa - El Rey León",
    "Scar - El Rey León",
    "Nala - El Rey León",
    "Timón - El Rey León",
    "Pumba - El Rey León",
    "Rafiki - El Rey León",

    // Hércules
    "Hércules - Hércules",
    "Megara - Hércules",
    "Hades - Hércules",
    "Phil - Hércules",
    "Pegaso - Hércules",

    // El Jorobado de Notre Dame
    "Quasimodo - El Jorobado de Notre Dame",
    "Esmeralda - El Jorobado de Notre Dame",
    "Frollo - El Jorobado de Notre Dame",

    // Pixar
    "Woody - Toy Story",
    "Buzz Lightyear - Toy Story",
    "Jessie - Toy Story",
    "Rex - Toy Story",
    "Mike Wazowski - Monstruos S.A.",
    "Sulley - Monstruos S.A.",
    "Boo - Monstruos S.A.",
    "Nemo - Buscando a Nemo",
    "Dory - Buscando a Nemo",
    "Marlin - Buscando a Nemo",
    "WALL-E - WALL-E",
    "EVE - WALL-E",
    "Señor Fredricksen - UP",
    "Russell - UP",
    "Dug - UP",
    "Rayo McQueen - Cars",
    "Mate - Cars",
    "Joy - Intensa-Mente",
    "Tristeza - Intensa-Mente",
    "Miedo - Intensa-Mente",
    "Ira - Intensa-Mente",
    "Asco - Intensa-Mente",
    "Hiro Hamada - Big Hero 6",
    "Baymax - Big Hero 6",
    "Miguel - Coco",
    "Héctor - Coco",
    "Dante - Coco",
    "Imelda - Coco",
    "Mirabel - Encanto",
    "Bruno - Encanto",
    "Luisa - Encanto",
    "Isabela - Encanto",
    "Dolores - Encanto",
    "Camilo - Encanto",
    "Casita - Encanto",

    // Zootopia y otros modernos
    "Nick Wilde - Zootopia",
    "Judy Hopps - Zootopia",
    "Vanellope - Ralph Rompe Internet",
    "Ralph - Ralph Rompe Internet",
    "Luca - Luca",
    "Alberto - Luca",

    // Películas (sin personaje específico)
    "Atlantis: El Imperio Perdido",
    "Lilo & Stitch",
    "El Libro de la Selva",
    "Los Increíbles",
    "Ratatouille",
  ],
  Perú: [
    // Lugares
    "Machu Picchu",
    "Cusco",
    "Arequipa",
    "Lima",
    "Miraflores",
    "La Molina",
    "Javier Prado",
    "Gamarra",
    "Larcomar",
    "Lago Titicaca",
    "Huacachina",
    "Líneas de Nazca",
    "Chan Chan",
    "Huascarán",
    "Callao",
    "Barranco",

    // Comida
    "Ceviche",
    "Lomo Saltado",
    "Ají de Gallina",
    "Anticuchos",
    "Causa Limeña",
    "Rocoto Relleno",
    "Papa a la Huancaína",
    "Pollo a la Brasa",
    "Chicha Morada",
    "Inca Kola",
    "Picarones",
    "Turrón de Doña Pepa",
    "Pan con Chicharrón",
    "Leche de Tigre",

    // Cultura / Tradiciones
    "Inti Raymi",
    "Señor de los Milagros",
    "Marinera",
    "Huayno",
    "Danza de las Tijeras",
    "Caballo de Paso",
    "Retablo Ayacuchano",
    "Torito de Pucará",

    // Personajes
    "Paolo Guerrero",
    "Claudio Pizarro",
    "Gianluca Lapadula",
    "Gastón Acurio",
    "Susy Díaz",
    "Laura Bozzo",
    "Chabuca Granda",
    "Pedro Suárez-Vértiz",

    // TV / Cultura Pop
    "Al Fondo Hay Sitio",
    "Esto es Guerra",
    "Habacilar",
    "Pataclaun",
    "La Paisana Jacinta",
    "El Whasap de JB",

    // Jergas Peruanas
    "¡Asu mare!",
    "¡Que Palta!",
    "¡Que Piña!",
    "¡Que Roche!",
    "Chévere",
    "Pata",
    "Causa",
    "Chamba",
    "Jato",
    "Flaca",
    "Tono",
    "Chibolo",
    "Achorao",
    "Monse",
    "¡Estoy aguja!",
    "Yara ",
    "Manyas",
    "No seas sapo",
    "Misio",

    // Transporte / Cosas Cotidianas
    "Combi",
    "Metropolitano",
    "Mototaxi",
    "Tico",
    "Custer",
    "Peaje",
    "Serenazgo",
    "Sunat",
    "DNI",
    "Reniec",

    // Marcas / Empresas
    "BCP",
    "Interbank",
    "Plaza Vea",
    "Tottus",
    "Saga Falabella",
    "Ripley",
    "Cineplanet",
    "Inkafarma",
    "MiFarma",

    // Naturaleza / Fauna
    "Alpaca",
    "Vicuña",
    "Cóndor Andino",
    "Gallito de las Rocas",
    "Llama",
    "Pisco",
    "Amazonía",
    "Cordillera Blanca"
  ],
};

export function pickRandomWord(category: string) {
  const list = wordBank[category] ?? [];
  if (!list.length) return null;
  const idx = Math.floor(Math.random() * list.length);
  return list[idx];
}
