export const wordBank: Record<string, string[]> = {
Películas: [
  "El Padrino",
  "Titanic",
  "Avatar",
  "Avengers: Endgame",
  "Jurassic Park",
  "Star Wars",
  "El Caballero Oscuro",
  "Forrest Gump",
  "Gladiador",
  "El Señor de los Anillos: La Comunidad del Anillo",
  "Harry Potter y la piedra filosofal",
  "Matrix",
  "El Rey León",
  "Toy Story",
  "Buscando a Nemo",
  "Frozen",
  "Shrek",
  "Los Increíbles",
  "Up",
  "Coco",
  "Interestelar",
  "Origen",
  "Parásitos",
  "Joker",
  "Spider-Man: No Way Home",
  "Iron Man",
  "Black Panther",
  "Doctor Strange",
  "Deadpool",
  "Rápidos y Furiosos",
  "Misión Imposible",
  "Piratas del Caribe: La maldición del Perla Negra",
  "Rocky",
  "Rambo",
  "Terminator",
  "Volver al Futuro",
  "Indiana Jones y los cazadores del arca perdida",
  "E.T., el extraterrestre",
  "Tiburón",
  "El silencio de los inocentes",
  "El sexto sentido",
  "La lista de Schindler",
  "El club de la pelea",
  "El lobo de Wall Street",
  "El Gran Gatsby",
  "Casablanca",
  "Psicosis",
  "El resplandor",
  "Django sin cadenas",
  "Bastardos sin gloria",
  "El bueno, el malo y el feo",
  "Braveheart",
  "300",
  "La La Land",
  "Whiplash",
  "El pianista",
  "Amélie",
  "Intocable",
  "Slumdog Millionaire",
  "Mad Max: Furia en el camino",
  "John Wick",
  "El Conjuro",
  "It",
  "Scream",
  "El Exorcista",
  "Blade Runner",
  "Alien: El octavo pasajero",
  "Depredador",
  "El Código Da Vinci",
  "Los Juegos del Hambre",
  "Logan",
  "Wonder Woman",
  "Aquaman",
  "Thor",
  "Guardianes de la Galaxia",
  "Transformers",
  "Avatar: La forma del agua",
  "Bohemian Rhapsody",
  "El Gran Hotel Budapest",
  "El Laberinto del Fauno",
  "Roma",
  "Her",
  "The Truman Show",
  "El Gran Dictador",
  "La Vida es Bella",
  "El Discurso del Rey",
  "Argo",
  "Million Dollar Baby",
  "El Renacido",
  "Top Gun",
  "Gran Torino",
  "El Origen de los Guardianes",
  "La Teoría del Todo",
  "Moulin Rouge!",
  "El Quinto Elemento",
  "Suicide Squad",
  "Black Swan"
],
Series: [
  "Stranger Things",
  "Breaking Bad",
  "The Crown",
  "La Casa de Papel",
  "Narcos",
  "Chernobyl",
  "Game of Thrones",
  "The Sopranos",
  "Friends",
  "The Office",
  "Westworld",
  "Black Mirror",
  "Dark",
  "Peaky Blinders",
  "Mindhunter",
  "Ozark",
  "Élite",
  "The Mandalorian",
  "Vikings",
  "The Witcher",
  "Better Call Saul",
  "Fargo",
  "House of Cards",
  "Downton Abbey",
  "Sherlock",
  "Killing Eve",
  "The Boys",
  "The Handmaid's Tale",
  "Lucifer",
  "Broadchurch",
  "Dexter",
  "The Walking Dead",
  "This Is Us",
  "The Umbrella Academy",
  "Succession",
  "Mr. Robot",
  "The Haunting of Hill House",
  "Los Simuladores",
  "13 Reasons Why",
  "House",
  "Gomorrah",
  "True Detective",
  "Prison Break",
  "How I Met Your Mother",
  "Modern Family",
  "The Simpsons",
  "Rick and Morty",
  "BoJack Horseman",
  "Twin Peaks",
  "Mad Men",
  "The West Wing",
  "Homeland",
  "Borgen",
  "The Good Place",
  "The Expanse",
  "Lost",
  "Fringe",
  "The X-Files",
  "Avatar: The Last Airbender",
  "One Piece",
  "Attack on Titan",
  "My Hero Academia",
  "Death Note",
  "Cobra Kai",
  "The Shield",
  "Luther",
  "True Blood",
  "The Leftovers",
  "The Marvelous Mrs. Maisel",
  "Fleabag",
  "Hannibal",
  "Grey's Anatomy",
  "Shameless",
  "Silicon Valley",
  "Parks and Recreation",
  "The Big Bang Theory",
  "The Wire",
  "Seinfeld",
  "Brooklyn Nine-Nine",
  "The Last of Us",
  "Euphoria",
  "The Bear",
  "House of the Dragon",
  "Wednesday",
  "Bridgerton",
  "The Sandman",
  "Arcane",
  "Invincible",
  "The Queen's Gambit",
  "Money Heist: Korea",
  "Sense8",
  "Rome",
  "Spartacus",
  "Supernatural",
  "The OA",
  "Ted Lasso",
  "Yellowstone"
],
Personajes: [
  "Vito Corleone",
  "Michael Corleone",
  "Tony Montana",
  "Rocky Balboa",
  "Rambo",
  "Darth Vader",
  "Luke Skywalker",
  "Princesa Leia",
  "Han Solo",
  "Indiana Jones",
  "Forrest Gump",
  "Neo",
  "Terminator",
  "Ellen Ripley",
  "Jack Dawson",
  "Joker",
  "Batman",
  "Spider-Man",
  "Iron Man",
  "Capitán América",
  "Thor",
  "Black Panther",
  "Doctor Strange",
  "Deadpool",
  "Wolverine",
  "Harry Potter",
  "Hermione Granger",
  "Ron Weasley",
  "Gandalf",
  "Frodo Bolsón",
  "Aragorn",
  "Legolas",
  "Capitán Jack Sparrow",
  "Elsa",
  "Anna",
  "Simba",
  "Woody",
  "Buzz Lightyear",
  "Shrek",
  "Fiona",
  "Optimus Prime",
  "John Wick",
  "Maximus",
  "William Wallace",
  "Gladiador Máximo",
  "Travis Bickle",
  "El Padrino",
  "Hannibal Lecter",
  "Clarice Starling",
  "Freddy Krueger",
  "Michael Myers",
  "Jason Voorhees",
  "El Exorcista (Regan)",
  "Pennywise",
  "James Bond",
  "Rocky Dennis",
  "Marty McFly",
  "Doc Brown",
  "E.T.",
  "King Kong",
  "Godzilla",
  "Sherlock Holmes",
  "Drácula",
  "Frankenstein",
  "Tarzán",
  "Aladdin",
  "Genio",
  "Mufasa",
  "Scar",
  "Maléfica",
  "Cruella de Vil",
  "Cenicienta",
  "Blancanieves",
  "La Mujer Maravilla",
  "Aquaman",
  "Lara Croft",
  "Katniss Everdeen",
  "Jack Sparrow",
  "Edward Scissorhands",
  "El Lobo de Wall Street (Jordan Belfort)",
  "Tyler Durden",
  "Patrick Bateman",
  "El Hombre Araña",
  "Black Widow",
  "Thanos",
  "Hulk",
  "Dr. Emmett Brown",
  "Norman Bates",
  "El T-1000",
  "Robocop",
  "El Zorro",
  "Beetlejuice",
  "Rocky Balboa Jr.",
  "Anakin Skywalker",
  "Obi-Wan Kenobi",
  "Capitana Marvel"
],
Celebridades: [
  "Michael Jackson",
  "Elvis Presley",
  "Madonna",
  "Beyoncé",
  "Taylor Swift",
  "Rihanna",
  "Ariana Grande",
  "Lady Gaga",
  "Shakira",
  "Jennifer Lopez",
  "Justin Bieber",
  "Bruno Mars",
  "Drake",
  "The Weeknd",
  "Eminem",
  "Ed Sheeran",
  "Adele",
  "Kanye West",
  "Bad Bunny",
  "Karol G",
  "Leonardo DiCaprio",
  "Brad Pitt",
  "Angelina Jolie",
  "Tom Cruise",
  "Johnny Depp",
  "Will Smith",
  "Dwayne Johnson",
  "Robert Downey Jr.",
  "Scarlett Johansson",
  "Jennifer Lawrence",
  "Emma Watson",
  "Keanu Reeves",
  "Morgan Freeman",
  "Tom Hanks",
  "Meryl Streep",
  "Natalie Portman",
  "Chris Hemsworth",
  "Zendaya",
  "Margot Robbie",
  "Ryan Reynolds",
  "Lionel Messi",
  "Cristiano Ronaldo",
  "Neymar",
  "Kylian Mbappé",
  "LeBron James",
  "Michael Jordan",
  "Serena Williams",
  "Roger Federer",
  "Rafael Nadal",
  "Tiger Woods",
  "Muhammad Ali",
  "Usain Bolt",
  "Simone Biles",
  "Stephen Curry",
  "Lewis Hamilton",
  "David Beckham",
  "Pelé",
  "Diego Maradona",
  "Freddie Mercury",
  "Bob Marley",
  "Whitney Houston",
  "Prince",
  "David Bowie",
  "Kurt Cobain",
  "Mick Jagger",
  "Paul McCartney",
  "John Lennon",
  "Britney Spears",
  "Christina Aguilera",
  "Billie Eilish",
  "Selena Gomez",
  "Kim Kardashian",
  "Kylie Jenner",
  "Oprah Winfrey",
  "Ellen DeGeneres",
  "Jimmy Fallon",
  "MrBeast",
  "PewDiePie",
  "Mark Zuckerberg",
  "Elon Musk",
  "Bill Gates",
  "Steve Jobs",
  "Jeff Bezos",
  "Barack Obama",
  "Donald Trump",
  "Joe Biden",
  "Vladimir Putin",
  "Papa Francisco",
  "Reina Isabel II",
  "Princesa Diana",
  "Jackie Chan",
  "Bruce Lee",
  "Sylvester Stallone",
  "Arnold Schwarzenegger",
  "Jim Carrey",
  "Robert De Niro",
  "Al Pacino",
  "Quentin Tarantino"
],
Animales: [
  "Perro",
  "Gato",
  "León",
  "Tigre",
  "Elefante",
  "Jirafa",
  "Cebra",
  "Caballo",
  "Vaca",
  "Toro",
  "Oveja",
  "Cabra",
  "Cerdo",
  "Conejo",
  "Lobo",
  "Zorro",
  "Oso",
  "Panda",
  "Koala",
  "Canguro",
  "Chimpancé",
  "Gorila",
  "Orangután",
  "Rinoceronte",
  "Hipopótamo",
  "Cocodrilo",
  "Aligátor",
  "Serpiente",
  "Águila",
  "Halcón",
  "Búho",
  "Loro",
  "Pingüino",
  "Avestruz",
  "Pavo real",
  "Gallina",
  "Gallo",
  "Pato",
  "Cisne",
  "Tiburón",
  "Delfín",
  "Ballena",
  "Orca",
  "Pulpo",
  "Calamar",
  "Medusa",
  "Estrella de mar",
  "Caballito de mar",
  "Foca",
  "León marino",
  "Morsa",
  "Camello",
  "Llama",
  "Alpaca",
  "Ardilla",
  "Castor",
  "Mapache",
  "Hurón",
  "Erizo",
  "Hámster",
  "Ratón",
  "Rata",
  "Murciélago",
  "Pantera",
  "Leopardo",
  "Guepardo",
  "Hiena",
  "Bisonte",
  "Ciervo",
  "Venado",
  "Antílope",
  "Búfalo",
  "Carnero",
  "Chivo",
  "Puma",
  "Jaguar",
  "Mono",
  "Perezoso",
  "Tortuga",
  "Iguana",
  "Camaleón",
  "Rana",
  "Sapo",
  "Salamandra",
  "Cangrejo",
  "Langosta",
  "Hormiga",
  "Abeja",
  "Mariposa",
  "Escorpión",
  "Araña",
  "Caracol",
  "Babosa",
  "Gaviota",
  "Colibrí",
  "Cuervo",
  "Paloma"
],
Comida: [
  "Pizza",
  "Hamburguesa",
  "Hot dog",
  "Sushi",
  "Ramen",
  "Tacos",
  "Burrito",
  "Quesadilla",
  "Nachos",
  "Paella",
  "Tortilla española",
  "Gazpacho",
  "Pasta",
  "Lasaña",
  "Espagueti",
  "Risotto",
  "Gnocchi",
  "Ravioli",
  "Pollo frito",
  "Alitas de pollo",
  "Barbacoa",
  "Costillas BBQ",
  "Filete",
  "Ensalada César",
  "Sopa de tomate",
  "Crema de champiñones",
  "Curry",
  "Ají de gallina",
  "Falafel",
  "Hummus",
  "Kebab",
  "Shawarma",
  "Empanadas",
  "Arepas",
  "Ceviche",
  "Tamales",
  "Churros",
  "Croissant",
  "Baguette",
  "Panqueques",
  "Waffles",
  "Donas",
  "Brownies",
  "Cupcakes",
  "Pastel de chocolate",
  "Cheesecake",
  "Tiramisú",
  "Gelato",
  "Helado",
  "Flan",
  "Arroz con leche",
  "Mousse de chocolate",
  "Macarrones",
  "Pudín",
  "Galletas",
  "Sandwich",
  "Club sandwich",
  "Tostadas",
  "Huevos revueltos",
  "Omelette",
  "Bacon",
  "Salchichas",
  "Mariscos",
  "Langosta",
  "Camarones",
  "Pulpo a la gallega",
  "Sashimi",
  "Tempura",
  "Dim sum",
  "Rollitos primavera",
  "Pad Thai",
  "Pho",
  "Bibimbap",
  "Kimchi",
  "Goulash",
  "Fondue",
  "Ratatouille",
  "Pierogi",
  "Feijoada",
  "Asado",
  "Milanesa",
  "Chili con carne",
  "Guacamole",
  "Nachos con queso",
  "Papas fritas",
  "Puré de papa",
  "Arroz frito",
  "Arroz blanco",
  "Lentejas",
  "Sopa miso",
  "Enchiladas",
  "Fajitas",
  "Poke",
  "Tarta de manzana",
  "Crepes",
  "Salmón a la plancha",
  "Pollo asado",
  "Chaufa"
],
  Disney: [
    "Mickey Mouse",
    "Minnie Mouse",
    "Donald Duck",
    "Goofy",
    "Pluto",
    "Cenicienta",
    "Blancanieves",
    "La Bella Durmiente",
    "La Sirenita",
    "Aladdin",
    "El Rey León",
    "Frozen",
    "Enredados",
    "Señor Fredricksen",
    "Moana",
    "Coco",
    "Encanto",
    "Big Hero 6",
    "Rayo McQueen",
    "Toy Story",
    "Monstruos S.A.",
    "Buscando a Nemo",
    "UP",
    "WALL-E",
    "Valiente",
    "Intensa-Mente",
    "Inside Out",
    "Zootopia",
    "Ralph Rompe Internet",
    "La Princesa y el Sapo",
    "Mulán",
    "Alicia en el País de las Maravillas",
    "Pinocho",
    "Peter Pan",
    "Dumbo",
    "Bambi",
    "El Jorobado de Notre Dame",
    "Esmeralda",
    "Quasimodo",
    "Príncipe Naveen",
    "Jasmine",
    "Ariel",
    "Belle",
    "Elsa",
    "Anna",
    "Kristoff",
    "Olaf",
    "Sven",
    "Pumba",
    "Timón",
    "Scar",
    "Mufasa",
    "Nala",
    "Simba",
    "Rajah",
    "Abu",
    "Iago",
    "Jafar",
    "Ursula",
    "Príncipe Eric",
    "Gaston",
    "Megara",
    "Hércules",
    "Phil",
    "Pegaso",
    "Maléfica",
    "Aurora",
    "Flora",
    "Fauna",
    "Primavera",
    "Lobo Feroz",
    "El Espejo Mágico",
    "La Lámpara Maravillosa",
    "La Rosa Encantada",
    "Tiana",
    "Navín",
    "Dr. Facilier",
    "Carlota",
    "Luis",
    "Rapunzel",
    "Flynn Rider",
    "Pascal",
    "Gothel",
    "Maui",
    "Te Ka",
    "Tamatoa",
    "Abuela Motunui",
    "Miguel",
    "Dante",
    "Héctor",
    "Imelda",
    "Mirabel",
    "Bruno",
    "Casita",
    "Tití Irma",
    "Camilo",
    "Dolores",
    "Príncipe Azul",
    "Castillo Mágico",
    "Transformación Mágica",
    "Bola de Cristal",
    "Zapatilla de Cristal",
    "Fruta Prohibida",
    "Espejo Encantado",
    "Anillo Encantado",
    "Varita Mágica"
  ],
  Perú: [
    // TODO: Rellena con palabras/personajes/lugares peruanos
    // Ejemplo: "Machu Picchu", "Inti Raymi", "Quetzal", "Alpaca", etc.
  ]
};

export function pickRandomWord(category: string) {
  const list = wordBank[category] ?? [];
  if (!list.length) return null;
  const idx = Math.floor(Math.random() * list.length);
  return list[idx];
}
